config/routes.rb
Rails.application.routes.draw do
  get 'administration/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :update]
  resources :carts, only: [:show]
  resources :purchases, only: [:show]
  resources :cart_products, only: [:create]
  # TODO: learn to write routes
      post 'cart_products/:id/increment_product_quantity/', to: 'cart_products#increment_product_quantity', as: 'increment_product_quantity'
      post 'cart_products/:id/decrement_product_quantity/', to: 'cart_products#decrement_product_quantity', as: 'decrement_product_quantity'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'StickerShop', products_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', products_path, class: 'nav-link' %>
      </li>
      <!--  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
        </div>
        </li>
      -->
    <% if admin? %>
      <li class="nav-item">
        <%= link_to 'Administration', administration_index_path, class: 'nav-link' %>
      </li>
    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class='nav-item' aria-hidden="true" role="button">
          <%= link_to cart_path(current_user.cart.id), class: 'nav-link' do %>
            <i class="fa fa-shopping-cart"></i>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            <%= link_to 'Edit info', user_path(current_user), class: 'dropdown-item' %>
          <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'dropdown-item mr-auto' %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_notice.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>