config/routes.rb
Rails.application.routes.draw do
  get 'administration/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :update]
  resources :carts, only: [:show]
  resources :purchases, only: [:show]
  resources :cart_products, only: [:create]
  # TODO: learn to write routes
      post 'cart_products/:id/increment_product_quantity/', to: 'cart_products#increment_product_quantity', as: 'increment_product_quantity'
      post 'cart_products/:id/decrement_product_quantity/', to: 'cart_products#decrement_product_quantity', as: 'decrement_product_quantity'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products

  validates :user_id, presence: true

  scope :user_cart_with_products, -> (user) { includes(:cart_products, :products).find_by(user_id: user) }

  def amount
    self.cart_products.inject(0) { |sum, cp| sum + cp.quantity * cp.product.price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.user_cart_with_products(current_user)
  end
end

app/views/carts/show.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr> 
        <th></th>
        <th scope="col">Item</th>
        <th scope="col">Description</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit price</th>
        <th scope="col">Amount</th>
      </tr>
    </thead>
    <tbody>

      <% @cart.cart_products.each do |p| %>
        <tr>
          <td><%= link_to product_path(p.product) do %>
            <%= image_tag p.product.thumbnail if p.product.image.present? %>
        <% end %></td>
          <td><%= link_to p.product.name, product_path(p.product) %></td>
          <td><%= p.product.truncated_description %></td>
          <td><%= p.quantity %></td>
          <td><%= p.product.price %></td>
          <td><%= "#{p.product.price * p.quantity}€" %></td>
          <td class="btn-group">
            <%= button_to '-', decrement_product_quantity_path(p), class: 'btn btn-sm btn-secondary', method: :post %>
            <%= button_to '+', increment_product_quantity_path(p), class: 'btn btn-sm btn-primary', method: :post %>
          </td>
        </tr>
      <% end %>
        <tr>
          <td></td><td></td><td></td><td></td><td></td> 
          <td><%= @cart.amount %></td>
        </tr>

    </tbody>
  </table>
</div>