config/routes.rb
Rails.application.routes.draw do
  get 'administration/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :update]
  resources :carts, only: [:show]
  resources :purchases, only: [:show]
  resources :cart_products, only: [:create]
  # TODO: learn to write routes
      post 'cart_products/:id/increment_product_quantity/', to: 'cart_products#increment_product_quantity', as: 'increment_product_quantity'
      post 'cart_products/:id/decrement_product_quantity/', to: 'cart_products#decrement_product_quantity', as: 'decrement_product_quantity'
end

app/models/product.rb
class Product < ApplicationRecord
  PRODUCT_STATUS = {
    active: 1,
    deleted: 2,
    na: 3,
    out_of_stock: 4
  }.freeze

  belongs_to :supplier, class_name: 'User'
  has_one :product_category, dependent: :destroy
  has_one :category, through: :product_category
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :cart_products, dependent: :destroy
  has_many :carts, through: :cart_products
  has_many :purchase_products, dependent: :destroy
  has_many :purchases, through: :purchase_products
  has_one_attached :image

  validates :name, :description, :price, :quantity, :status, presence: true
  validates :price, :quantity, numericality: true
  validates_inclusion_of :status, in: PRODUCT_STATUS.values
  validates :supplier_id, presence: true

  def truncated_description
    self.description.truncate(50, separator: ' ', omission: '...')
  end

  def card_image
    resize_image(400, 200)
  end
  def gallery_image
    resize_image(600, 400)
  end
  def gallery_item
    resize_image(100, 50)
  end
  def thumbnail
    resize_image(50, 50)
  end

  private

  def resize_image(x, y)
    self.image.variant(resize_to_limit: [x, y]).processed
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :verify_authorization, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.with_attached_image.includes(:tags, :supplier).page(params[:page])
    @categories = Category.select(:id, :name)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product successfully created' }
      else
        format.html { render :new, notice: 'Error' }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Product successfuly destroyed' }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :status, :supplier_id, :image)
  end
end

app/views/products/_add_product_to_cart.html.erb
<% if user_signed_in? %>
  <%= button_to 'Add to cart', { controller: :cart_products,
                                 action: :create,
                                   cart_product: {
                                     product_id: product.id,
                                     cart_id: current_user.cart.id 
                                   },
                               },
                               method: 'post',
                               class: 'btn btn-success d-inline btn-sm' %> 
<% end %>

app/views/products/_delete_product_button.html.erb
<% if admin? %>
  <%= button_to 'Delete', { controller: :products,
                            action: 'destroy',
                            id: product.id },
                            method: :delete,
                            class: 'btn btn-danger d-inline btn-sm' %>
<% end %>

app/views/products/_edit_product_button.html.erb
<% if admin? %>
  <%= button_to 'Edit', edit_product_path(product), 
    method: 'get',
    class: 'btn btn-primary d-inline btn-sm' %>
<% end %>

app/views/products/_product.html.erb
<div class="card" style="width: 14rem;">
  <%= image_tag(product.card_image) if product.image.present? %>
  <div class="card-body">
    <h5 class="card-title text-dark"><%= link_to product.name, product_path(product) %></h5>
    <p class='small text-right'> by <%= link_to product.supplier.email, user_path(product.supplier), class: 'small' %></p>
    <p class="card-text"><%= product.truncated_description %></p>
    <div class="text-left d-inline">
      <div class="btn-group">
        <%= render partial: 'edit_product_button', object: product, as: :product %>
        <%= render partial: 'delete_product_button', object: product, as: :product %>
      </div>
    </div>
    <div class="text-right d-inline">
      <div class="btn-group">
        <%= render partial: 'view_product_button', object: product, as: :product %>
        <%= render partial: 'add_product_to_cart', object: product, as: :product %>
      </div>
    </div>
    <% product.tags.each do |tag| %>
      <span class='badge badge-pill badge-secondary'><%= tag.name %></span>
    <% end %>
  </div>
</div>

app/views/products/_product_form.html.erb
<%= form_with model: @product, multipart: true, local: true do |f| %>

   <div class="field form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :quantity%>
      <%= f.number_field :quantity, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <%= f.hidden_field :status, value: 1 %>

    <div class="actions">
      <%= f.submit class:"btn btn-primary" %>
    </div>

<% end %>

app/views/products/_view_product_button.html.erb
<% if admin? %>
  <%= button_to 'More', product_path(product), 
    method: 'get',
    class: 'btn btn-info d-inline btn-sm' %>
<% end %>

app/views/products/edit.html.erb
<%= render partial: 'product_form', object: @product %>

app/views/products/index.html.erb
<% if admin? %>
  <div class='jumbotron'>
    <%= button_to 'New product', new_product_path, method: :get, class: 'btn btn-lg btn-block btn-outline-success' %>
    <%= button_to 'Manage products', new_product_path, method: :get, class: 'btn btn-lg btn-block btn-outline-info' %>
  </div>
<% end %>

<div class='container'>
  <div class='row' >
    <div class="col-2 border border-primary rounded-right pt-3 pl-3 ml-3 mr-5">
      <p>CATEGORIES</p>
      <ul class="nav flex-column">
        <% @categories.each do |category| %>
          <%= link_to category.name, '#' %>
        <% end %>
        <li class="nav-item">
        </li>
      </ul>
    </div>
    <div class="col">
      <div class='row mx-auto' >
        <%= render partial: 'product', collection: @products %>
      </div>
    </div>
  </div>
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'product_form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container bg-light">
  <div class="row">
    <div class="col-lg-6">
      <%= image_tag @product.gallery_image if @product.image.present? %>
    </div>
    <div class="col-lg-6 mt-3">
      <div class="row">
        <div class="col-4"><h2><%= @product.name %></h2></div>
        <div class="col-8"><%= @product.supplier.email %></div>
        <div class="col"><p><%= @product.description %></p></div>
        <div class="col-lg-3 offset-8"><p>Price: <%= @product.price %>€</p></div>

        <div class ="col sticky-bottom">
      <%= render partial: 'delete_product_button', object: @product, as: :product %>
      <%= render partial: 'edit_product_button', object: @product, as: :product %>
      <%= render partial: 'add_product_to_cart', object: @product, as: :product %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>